name: Upld2BlobStorage

on:
  push:
    paths:                                  
      - ".github/workflows/pipeline.yml"

  
jobs:

  job1:
      name: Push Feature
      runs-on: ubuntu-latest
      environment: 
        name: Adls 
      steps:
        # checkout the repo
        - uses: actions/checkout@v2
        
        
        #JSON file to validate check
        - uses: Zingabopp/JsonValidate-Action@v1
          with:
            json-schema: JSONValidation/schema.json
            json-file: JSONValidation/test.json
          
        #If validation NOT passed, stops******************************************
        #Else, upload to storage ADLS*********************************************

        #LogIn to Azure with Service Principal Credentials 
        - name: Login via Az module
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURECREDENTIALS}}
            enable-AzPSSession: true 

        #Use az cmdlets to interact with ADLS gen2
        - name: Run Azure PowerShell script
          uses: azure/powershell@v1
          with:
            inlineScript: |
             az storage fs file upload -s "JSONValidation/test.json" -p "test.json"  -f "carloscontainer" --account-name "adlspocactions" --account-key ${{secrets.STORAGEKEY}}
            azPSVersion: "latest"

 



      
